function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 02-Mar-2022 11:16:15

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.0771428571428571 0.0947619047619048 0.866071428571429 0.868333333333337]);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Mexico');
set(plot1(2),'DisplayName','France');
set(plot1(3),'DisplayName','Australia');
set(plot1(4),'DisplayName','Germany');

% The following line demonstrates an alternative way to create a data tip.
% datatip(plot1(3),3,1.89);
% Create datatip
datatip(plot1(3),'DataIndex',3);

box(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');

